"""Local discovery vocabulary. These are transparent heuristics, not an ML model."""

DRIVER_MARKERS = (
    " driver ",
    " device driver ",
    " display driver ",
    " graphics driver ",
    " audio driver ",
    " chipset driver ",
    " network driver ",
    " printer driver ",
    " bluetooth driver ",
    " wireless driver ",
    " driver package ",
    " firmware ",
    " kernel driver ",
)

UNNECESSARY_MARKERS = (
    " uninstall ",
    " uninstaller ",
    " setup ",
    " installer ",
    " updater ",
    " update service ",
    " crash reporter ",
    " crashreporter ",
    " crashpad handler ",
    " telemetry service ",
    " maintenance service ",
    " redistributable ",
    " redist ",
    " runtime installer ",
    " repair tool ",
)

UNNECESSARY_BASENAMES = {
    "uninstall.exe",
    "uninstaller.exe",
    "unins000.exe",
    "unins001.exe",
    "setup.exe",
    "installer.exe",
    "update.exe",
    "updater.exe",
    "crashreporter.exe",
    "crashpad_handler.exe",
    "helper.exe",
    "service.exe",
    "maintenanceservice.exe",
    "vc_redist.x86.exe",
    "vc_redist.x64.exe",
    "dxsetup.exe",
    "msiexec.exe",
}

SYSTEM_PATH_MARKERS = (
    "\\windows\\system32\\",
    "\\windows\\syswow64\\",
    "\\windows\\winsxs\\",
    "\\windows\\servicing\\",
    "\\windows\\installer\\",
    "\\windows\\systemapps\\",
    "\\windows\\regedit.exe",
    "\\windows\\explorer.exe",
)

GAME_PATH_MARKERS = (
    "\\games\\",
    "\\steamapps\\common\\",
    "\\gog games\\",
    "\\xboxgames\\",
    "\\epic games\\",
    "\\riot games\\",
    "\\ubisoft game launcher\\games\\",
    "\\ea games\\",
)

GAME_PUBLISHER_MARKERS = (
    "valve",
    "ubisoft",
    "electronic arts",
    "ea games",
    "rockstar games",
    "bethesda",
    "bandai namco",
    "square enix",
    "capcom",
    "sega",
    "activision",
    "blizzard",
    "cd projekt",
    "riot games",
    "2k games",
    "take two",
    "paradox interactive",
    "warner bros games",
    "fromsoftware",
)

KNOWN_LAUNCHER_MARKERS = (
    "steam",
    "epic games launcher",
    "gog galaxy",
    "ubisoft connect",
    "ea app",
    "battle net",
    "rockstar games launcher",
    "xbox app",
    "riot client",
    "unreal editor",
    "unity editor",
    "unity hub",
    "playnite",
    "launchbox",
    "bluestacks",
    "faceit",
    "discord",
)

APP_MARKERS = (
    " browser ",
    " editor ",
    " office ",
    " studio ",
    " manager ",
    " player ",
    " client ",
    " terminal ",
    " powershell ",
    " calculator ",
    " recorder ",
    " viewer ",
    " launcher ",
    " control panel ",
    " utility ",
    " tools ",
    " desktop ",
    " word ",
    " excel ",
    " powerpoint ",
    " outlook ",
    " firefox ",
    " chrome ",
    " edge ",
    " blender ",
)
